### ISSUE TITLE
Question about file locations....

### ISSUE THREAD

**Issue by Dylan-Chapman** [danbroooks/gulp-phantomcss#3]
How do you save screenshots to a different folder? I can't change them in phantomcss.init() ("has no method 'init'"), and it doesn't work passing the options directly into phantomcss(). I'm new to gulp in general, and more so this, so any direction would be appreciated.

The options I was testing are screenshotRoot and failedComparisonsRoot. 

Are these options available and I'm overlooking how to do it?

**Comment by awayken** [comment]
@Dylan-Chapman: I don't know much about this Gulp plugin, but in reading the code there appear to be the following options you can pass in:

  * screenshots: path for screenshots
  * results: path for results?
  * viewportSize: array of [ width, height ] establishing viewport
  * logLevel: what level of message should be logged

That's what I see, but all I can do is to guess at what the different options mean and do.

Here's a snippet of how you might change the screenshot and results paths:

```javascript
gulp.task('phantomcss', function() {
    var phantomcss = require('gulp-phantomcss');

    return gulp.src('./test/styles/phantomcss.js')
        .pipe( phantomcss({
            screenshots: './test/styles/screenshots',
            results: './test/styles/results'
        }) );
});
```

**Comment by awayken** [comment]
logLevel seems to correspond to CasperJS logging levels: http://docs.casperjs.org/en/latest/logging.html

**Comment by danbroooks** [comment]
Updated the README to hopefully make things a bit clearer.
