### ISSUE TITLE
casper.test property is not available 

### ISSUE THREAD

**Issue by LoicGoyet** [danbroooks/gulp-phantomcss#4]
I've made the same simple task that on the doc :

```
gulp.task('phantomcss', function (){
    gulp.src('./testsuite.js')
        .pipe(phantomcss());
});
```

When I run the command `gulp phantomcss` the terminal output this :
```
CasperError: casper.test property is only available using the `casperjs test` command
```

Any idea ? For the record I did not install casper in my project, but it's installed on my computer.

**Comment by danbroooks** [comment]
Hi @LoicGoyet, is this on Windows or on Linux/Mac ?

**Comment by danbroooks** [comment]
Hi @LoicGoyet, did you install casper via the installer on their website? or did you install via npm `npm -g casperjs` ?

**Comment by LoicGoyet** [comment]
@danbroooks  I installed it via `npm -g casperjs`.

Sorry for the delay of the awser :s

**Comment by DevFacts** [comment]
Hey guys, i was facing the same issue, here i got a proper solution with nice explanation 
http://codefew.com/casper-test-property-is-not-available
Read the tutorial 
Thanks to CodeFew.com
